export const FETCH_MOVIE_COLLECTION_REQUEST = 'FETCH_MOVIE_COLLECTION_REQUEST';
export const FETCH_MOVIE_COLLECTION_SUCCESS = 'FETCH_MOVIE_COLLECTION_SUCCESS';
export const FETCH_MOVIE_COLLECTION_FAILURE = 'FETCH_MOVIE_COLLECTION_FAILURE';
export const FETCH_ALL_MOVIES = 'FETCH_ALL_MOVIES';
export const MOVIE_CATEGORY_FILTER = 'MOVIE_CATEGORY_FILTER';
